import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { ChakraProvider } from '@chakra-ui/react'
import { AuthProvider } from "./context/AuthContext";
import ProtectedRoute from "./_components/ProtectiveRoute";
import Footer from "./_components/Footer";
import Head from "next/head";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "TechCanva",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>

        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5317982228910759"
          crossorigin="anonymous"></script>
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>

          <ChakraProvider>
            <ProtectedRoute>

              <Navbar />
              {children}
              <Footer />
            </ProtectedRoute>
          </ChakraProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
