import { Inter } from 'next/font/google';
import "./globals.css";
import Navbar from "./_components/Navbar";
import { ChakraProvider } from '@chakra-ui/react';
import { AuthProvider } from "./context/AuthContext";
import ProtectedRoute from "./_components/ProtectiveRoute";
import Footer from "./_components/Footer";
import Head from "next/head";
import { ThemeProvider } from "@/components/theme-provider";
import StaticCallButton from './_components/CallButton';
import Script from 'next/script';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata = {
  title: "TechCanva",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <Script
          id="meta-pixel"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              !function(f,b,e,v,n,t,s)
              {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
              n.callMethod.apply(n,arguments):n.queue.push(arguments)};
              if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
              n.queue=[];t=b.createElement(e);t.async=!0;
              t.src=v;s=b.getElementsByTagName(e)[0];
              s.parentNode.insertBefore(t,s)}(window, document,'script',
              'https://connect.facebook.net/en_US/fbevents.js');
              fbq('init', '1521058109016649');
              fbq('track', 'PageView');
            `,
          }}
        />
        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src={`https://www.facebook.com/tr?id=1521058109016649&ev=PageView&noscript=1`}
          />
        </noscript>
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5317982228910759"
          crossorigin="anonymous"></script>
          
      </Head>
      <body className={inter.className}>
        <AuthProvider>
          <ChakraProvider>
            <ProtectedRoute>
              <ThemeProvider
                attribute="class"
                defaultTheme="dark"
                enableSystem
                disableTransitionOnChange
              >
                <Navbar />
                {children}
                <StaticCallButton/>
                <Footer />
              </ThemeProvider>
            </ProtectedRoute>
          </ChakraProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
