import { Inter } from 'next/font/google';
import "./globals.css";
import Navbar from "./_components/Navbar";
import { ChakraProvider } from '@chakra-ui/react';
import { AuthProvider } from "./context/AuthContext";
import ProtectedRoute from "./_components/ProtectiveRoute";
import Footer from "./_components/Footer";
import Head from "next/head";
import { ThemeProvider } from "@/components/theme-provider";
import StaticCallButton from './_components/CallButton';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata = {
  title: "TechCanva",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5317982228910759"
          crossorigin="anonymous"></script>
      </Head>
      <body className={inter.className}>
        <AuthProvider>
          <ChakraProvider>
            <ProtectedRoute>
              <ThemeProvider
                attribute="class"
                defaultTheme="dark"
                enableSystem
                disableTransitionOnChange
              >
                <Navbar />
                {children}
                <StaticCallButton/>
                <Footer />
              </ThemeProvider>
            </ProtectedRoute>
          </ChakraProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
